version: '3.8'
services:
  app:
    image: ${DOCKER_REPO_NAME}:${DOCKER_IMAGE_VERSION_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

  promtail:
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE_ADDR_LOKI_PORT: ${MONITORING_INSTANCE_ADDR_LOKI_PORT}
      ENVIRONMENT: dev
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./log:/log
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    networks:
      - edukit_network

networks:
  edukit_network:
    driver: bridge
