version: '3.8'
services:
  app:
    image: ${DOCKER_REPO_NAME}:${DOCKER_IMAGE_VERSION_TAG}
    environment:
      PROFILE: prod
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log:/log

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE_LOKI: ${MONITORING_INSTANCE_LOKI}
      ENVIRONMENT: prod
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./log:/log
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    restart: always
