version: '3.8'
services:
  app-blue:
    container_name: app-blue
    image: ${DOCKER_REPO_NAME}:${DOCKER_IMAGE_VERSION_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log:/log
    networks:
      - app-network

  app-green:
    container_name: app-green
    image: ${DOCKER_REPO_NAME}:${DOCKER_IMAGE_VERSION_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
    ports:
      - "8081:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log:/log
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ~/nginx-conf/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ~/nginx-conf/service-url.inc:/etc/nginx/conf.d/service-url.inc
    restart: always
    networks:
      - app-network

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE_LOKI: ${MONITORING_INSTANCE_LOKI}
      ENVIRONMENT: dev
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./log:/log
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    restart: always

networks:
  app-network:
    driver: bridge
