server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${MONITORING_INSTANCE_LOKI}/loki/api/v1/push"

scrape_configs:
  - job_name: error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: error_logs
          environment: ${ENVIRONMENT}
          __path__: /log/error/app.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            logType: logType
            requestId: requestId
            userId: userId
            httpMethod: httpMethod
            requestUri: requestUri
            statusCode: statusCode
            sourceClass: sourceClass
            sourceMethod: sourceMethod
            exceptionClass: exceptionClass
            exceptionMessage: exceptionMessage
            module: module
            environment: environment
            message: message
      - labels:
          level:
          logger:
          logType:
          requestId:
          userId:
          httpMethod:
          requestUri:
          statusCode:
          sourceClass:
          sourceMethod:
          exceptionClass:
          exceptionMessage:
          module:
          environment:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000Z07:00
          location: "Asia/Seoul"

  - job_name: info_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: info_logs
          environment: ${ENVIRONMENT}
          __path__: /log/info/app.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            logType: logType
            requestId: requestId
            userId: userId
            httpMethod: httpMethod
            requestUri: requestUri
            statusCode: statusCode
            sourceClass: sourceClass
            sourceMethod: sourceMethod
            exceptionClass: exceptionClass
            exceptionMessage: exceptionMessage
            module: module
            environment: environment
            message: message
      - labels:
          level:
          logger:
          logType:
          requestId:
          userId:
          httpMethod:
          requestUri:
          statusCode:
          sourceClass:
          sourceMethod:
          exceptionClass:
          exceptionMessage:
          module:
          environment:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000Z07:00
          location: "Asia/Seoul"

  - job_name: warn_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: warn_logs
          environment: ${ENVIRONMENT}
          __path__: /log/warn/app.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            logType: logType
            requestId: requestId
            userId: userId
            httpMethod: httpMethod
            requestUri: requestUri
            statusCode: statusCode
            sourceClass: sourceClass
            sourceMethod: sourceMethod
            exceptionClass: exceptionClass
            exceptionMessage: exceptionMessage
            module: module
            environment: environment
            message: message
      - labels:
          level:
          logger:
          logType:
          requestId:
          userId:
          httpMethod:
          requestUri:
          statusCode:
          sourceClass:
          sourceMethod:
          exceptionClass:
          exceptionMessage:
          module:
          environment:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000Z07:00
          location: "Asia/Seoul" 
