== 공지사항

=== 공지사항 목록 조회

==== 성공

operation::notice/get-success[snippets="query-parameters,http-request,http-response"]

=== 공지사항 상세 조회

==== 성공

operation::notice/get-one-success[snippets="path-parameters,http-request,http-response"]

==== 실패: 해당 공지사항이 존재하지 않음

operation::notice/get-one-fail-not-found[snippets="http-request,http-response"]

=== 공지사항 작성

==== 성공

operation::notice/create-success[snippets="request-fields,http-request,http-response"]

==== 실패: 작성할 수 없는 카테고리(ALL)

operation::notice/create-fail-invalid-category[snippets="request-fields,http-request,http-response"]

=== 공지사항 수정

==== 성공

operation::notice/update-success[snippets="path-parameters,request-fields,http-request,http-response"]

==== 실패: 해당 공지사항이 존재하지 않음

operation::notice/get-one-fail-not-found[snippets="http-request,http-response"]

=== 공지사항 삭제

==== 성공

operation::notice/delete-success[snippets="path-parameters,http-request,http-response"]

==== 실패: 해당 공지사항이 존재하지 않음

operation::notice/get-one-fail-not-found[snippets="http-request,http-response"]
